import http from "k6/http";
import { check, group, sleep } from "k6";

export const options = {
  vus: 2,
  duration: "5s",
  // Apply a global tag to all metrics generated by this script
  tags: { test_run_id: `run_${Date.now()}`, environment: "staging" },
};

export default function () {
  // Group 1: Browsing the catalog
  group("User Journey: Browse Catalog", function () {
    // Tagging at the request level to categorize API types
    const reqParams = { tags: { api_tier: "frontend_api" } };
    const res = http.get(
      "https://httpbin.org/anything?product=shoes",
      reqParams,
    );

    check(res, { "Catalog loaded": (r) => r.status === 200 });
    sleep(1); // Think time between steps
  });

  // Group 2: Adding item to cart
  group("User Journey: Add To Cart", function () {
    const payload = JSON.stringify({ item_id: 12345, qty: 1 });
    const reqParams = {
      headers: { "Content-Type": "application/json" },
      tags: { api_tier: "backend_core" }, // Different tag for backend
    };

    const res = http.post("https://httpbin.org/post", payload, reqParams);

    // Tagging a specific check
    check(
      res,
      { "Item added": (r) => r.status === 200 },
      { check_type: "critical_business_logic" },
    );
    sleep(1);
  });
}
